
months_dictionary = {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "May",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Oct",
    "11": "Nov",
    "12": "Dec",
}

currency_dictionary = {
    'Russian Ruble' : 'RUB',
    'Australian Dollar': 'AUD',
    'Canadian Dollar': 'CAD',
    'Chinese Yuan': 'CNY',
    'Czech Koruna': 'CZK',
    'Danish Krone': 'DKK',
    'Euro': 'EUR',
    'Hong Kong Dollar': 'HKD',
    'Hungarian Forint': 'HUF',
    'Indian Rupee': 'INR',
    'Israeli Shekel': 'ILS',
    'Japanese Yen': 'JPY',
    'Malaysian ringgit': 'MYR',
    'New Zealand Dollar': 'NZD',
    'Norwegian Krone': 'NOK',
    'Polish Zloty': 'PLN',
    'Saudi Riyal': 'SAR ',
    'Singapore Dollar': 'SGD',
    'South African Rand': 'ZAR',
    'South Korean Won': '',
    'Swedish Krona': '',
    'Swiss Franc': 'CHF',
    'Taiwan Dollar': 'TWD',
    'Thai Baht': 'THB',
    'Turkish Lira': 'TRY',
    'US Dollar': 'USD',
}